<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Simple Sidebar - Start Bootstrap Template</title>


    <!-- Bootstrap core CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/simple-sidebar.css" rel="stylesheet">


</head>

<body>

<div id="wrapper">

    <!-- Sidebar -->
    <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <li class="sidebar-brand">
                <div id="paginaIndex"><img src="http://essentia.com.br/wp-content/uploads/2014/11/elementos_logo11.png"
                                           class="logo"></div>
            </li>
            <li>
                <div id="paginaListagem">Listagem</div>
            </li>
            <li>
                <div id="paginaCadastro">Cadastro</div>
            </li>
        </ul>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper" class="index">
        <div class="container-fluid">
            <h1>Sistema de Cadastro de Clientes</h1>
            <p>Sistema CRUD simples, para clientes.</p>
            <a href="#menu-toggle" class="btn btn-secondary" id="menu-toggle">Vamos Começar!</a>
        </div>
    </div>

    <div id="page-content-wrapper" class="listagem">
        <div class="container-fluid">
            <h1>Listagem</h1>
            <div id="listagemClientes">
                <?php

                foreach ($this->view->cliente as $clientes) {

                    echo '<div class="row">';
                    echo '<div class="col-md-2 " >';
                    echo '<img src ="' . $clientes["endereco"] . '" class="view">';
                    echo '</div >';
                    echo '<div class="col-md-3 cont" style="border:1px solid">';
                    echo $clientes["nome"];
                    echo '</div >';
                    echo '<div class="col-md-2 cont" style="border:1px solid">';
                    echo $clientes["telefone"];
                    echo '</div >';
                    echo '<div class="col-md-3 cont" style="border:1px solid">';
                    echo $clientes["email"];
                    echo '</div >';
                    echo '<div class="col-md-2 acoes" >';
                    echo "<div id='" . $clientes["id"] . "' class='btn excluir'>Excluir</div>";
                    echo "<div id='" . $clientes["id"] . "' class='btn editar'>Editar</div>";
                    echo '</div >';
                    echo '</div >';

                }
                ?>
            </div>
            <div id="myModal" class="modal">

                <!-- Modal content -->
                <div class="modal-content">
                    <span class="close">&times;</span>
                    <div id="popup" class="popup"></div>
                    <div id="modal-edicao" class="modal-edicao">
                        <form id="alteracao" name="alteracao" enctype="multipart/form-data">
                            <img class="view">
                            <input type="file" name="foto_alteracao" id="foto_alteracao" value="">
                            <input type="hidden" name="id_alteracao" id="id_alteracao" value="0">
                            <div class="form-group">
                                <label for="nome_alteracao">Nome</label>
                                <input type="text" class="form-control" name="nome_alteracao" id="nome_alteracao"
                                       required="required">
                            </div>
                            <div class="form-group">
                                <label for="email_alteracao">Email</label>
                                <input type="email" class="form-control" name="email_alteracao" id="email_alteracao"
                                       required="required">
                            </div>
                            <div class="form-group">
                                <label for="telefone_alteracao">Telefone</label>
                                <input type="text" class="form-control" name="telefone_alteracao"
                                       id="telefone_alteracao"
                                       required="required">
                            </div>

                            <div class="row">
                                <input type="submit" class="btn btn-primary" value="alterar">
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div id="page-content-wrapper" class="cadastro">
        <div class="container-fluid">
            <h1>Cadastro de Clientes</h1>
            <form id="formulario" name="formulario" enctype="multipart/form-data">
                <div id="cad" class="row">
                    <div class="col-md-6 ">
                        <div class="form-group">
                            <label for="foto">Foto</label>
                            <input type="file" class="form-control" name="foto" id="foto" required="required">
                        </div>
                        <div class="form-group">
                            <label for="nome">Nome</label>
                            <input type="text" class="form-control" name="nome" id="nome" required="required">
                        </div>
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" name="email" id="email" required="required">
                        </div>
                        <div class="form-group">
                            <label for="telefone">Telefone</label>
                            <input type="text" name="telefone" class="form-control" id="telefone" required="required">
                        </div>
                    </div>

                </div>
                <div class="row">
                    <input type="submit" class="btn btn-primary" value="cadastrar">
                </div>
            </form>
        </div>
    </div>
    <!-- /#page-content-wrapper -->

</div>
<!-- /#wrapper -->

<!-- Bootstrap core JavaScript -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

<!--JavaScript Personalizado -->
<script src="vendor/js/init.js"></script>


</body>

</html>
